---
title: "Logboek-Geluk"
author: "Jarno Jacob Duiker"
date: "2024-05-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## tips
algemene introductie mist
Begin van de dag je doel al hebben en dat beschrijven per dag.
Heel erg in de diepte gaan van hoe het process verloopt. *STAP BIJ STAP*
Waarom, Hoe (zoektermen op googlescholar), Waarmee + uitkomst (critisch interpreteren - beschrijven van alles wat daarbij hoort)
Beredeneringen om waarom je dit uitvoert op de manier waarop je het doet. (gedachte gang)
literatuur lijst + kleine samenvatting waarom hij wel geschikt is (laat dingen zien uit het artikel)

## 22-04-2024

Vandaag heb ik de uitleg gekregen over wat in dit blok ik moet doen daarnaast ben ik bezig geweest met een begin van een plan. Dit plan gaat over wat storm en ik willen onderzoeken en hoe we dit met gekozen methodes kunnen en mogen doen. Hier is uitgekomen dat we het geluk van studenten gaan meten. Hier hebben in de les dus over gebrainstormed.

## 23-04-2024

Vandaag heb ik de hoofdvraag uitgewerkt wat er nodig is om een goed beeld te krijgen om deze te beantwoorden en welke literatuur er nodig en natuurlijk de hypothese en 0 hypothese. De hoofdvraag waar storm & ik het uiteindelijk over eens waren was

**“In welke studenten stad zijn studenten het gelukkigst?“**

Om deze vraag te kunnen beantwoorden moesten wij een manier verzinnen voor het meten van geluk. Storm & ik hebben hier over nagedacht en wij kwamen uit op een enquete die meerdere factoren behandeld over geluk. Deze factoren waar geluk van af hangt heb ik in de literatuur gevonden. Ook waren er 2 vragen die wij voor de achtergrond info moesten beantwoorden. Mijn 2 vragen waren “Wat is geluk (op een moleculair niveau)" & "Welke factoren dragen bij aan geluk?" Ik heb dus na school in de literatuur gekeken die te vinden is in de bronnen lijst en deze in eigenwoorden naar wat wij nodig hebben in een document gezet. Hiermee kon ik dus ook beginnen met het bedenken van de vragen

## 26-04-2024

Vandaag heb ik de eerste draft van mijn enquêtevragen gemaakt. Deze vragen zijn gebaseerd op wat ik in de literatuur vond. Ik heb mijn vragen grotendeels gebaseerd op de literatuur van de vraag "Welke factoren dragen bij aan geluk?". De vragen heb ik met storm besproken en we hebben zijn vragen bekeken. Deze vragen hebben daarna samengevoegd en doorgelezen. uit de ongeveer 25 vragen hebben we een tweede versie gemaakt die uitkwam op 15 vragen. Deze vragen hebben door onze project begeleider laten checken en hij zei de vragen waren goed echter kan je bij sommige vage antwoorden krijgen. We hebben deze vragen gemaakt zodat ze op een schaal van 0-10 kunnen worden beantwoord 0 = 0% en 10 = 100%. Nadat we dus de 2de versie hebben gemaakt zijn we begonnen met andere voorbereidingen. Ik heb de vragen in een google form gezet en deze aangemaakt. Terwijl storm met de posters begon.

## 29-04-2024

Vandaag zijn storm en ik met de trein naar leiden geweest. we waren tussen 13:10 & 13:20 op de eerste locatie van de universiteit van leiden. We zijn hier naar de service balie geweest en gevraagd waar de correcte plaats is om onze posters op te hangen. Wij hebben dit bij elk gebouw gedaan tenzij er een posterplek was waar aangegeven is dat dit mocht worden opgehangen. Onderweg hebben wij ook nog studenten proberen aan te spreken helaas kregen wij vaak het antwoord "Ik ben onderweg naar mijn les" of "ik ben druk" Nadat wij in elk gebouw op de universiteits campus 2 posters hebben gehangen zijn wij naar het LUMC gegaan en naar de campus van de hogeschool. Hier hebben wij ook op de poster borden de posters opgehangen.

## 07-05-2024

Vandaag zijn wij naar Utrecht geweest. Hetzelfde protocol als in leiden is hier gevolgd. Het vragen aan de service balie en verwezen worden naar de poster borden. We zijn hier om 13:00 op campus aangekomen. Hier hebben wij in de gebouwen van het HBO en de Universiteit Utrecht. Wanneer we de service balie medewerkers hier vroegen waar de posters mochten worden gehangen werd er. weer verwezen naar de posterborden.

## 08-05-2024

Tijdens de les ben ik bezig geweest met het verbeteren van de email die we naar de studieverenigingen, studenten verenigingen en de scholen willen sturen. Daarnaast ben ik bezig geweest met het netjes maken van mijn logboek zodat alles repliceerbaar is.

## 13-05-2024

Vandaag ben ik bezig geweest met het opzetten van het Rmarkdown document voor onze research paper. Ik heb de algemene structuur en de achtergrond info over wat geluk is en welke factoren hier bij horen in ons document gezet. Ik heb gekeken naar de voorbeelden die via de leraren zijn gegeven en de NCBI research papieren heb ik ook als voorbeeld genomen.

## 14-05-2024

Vandaag heb ik een klein beetje geholpen met email's verzamelen van studieverenigingen verder heb ik me ingelezen op de nieuwe opdracht die ons was gegeven over de spider plots. Storm en ik hebben hier ook nog gevraagd voor feedback op wat dingen en ik ben hier bezig geweest met het verbeteren. Dit houd in de structuur en de formulering van zowel het logboek als het algemene onderzoeks document.

## 15-05-2024

Storm en ik zijn vandaag op de zernike campus rond gaan lopen. Wij hebben in elk gebouw van de hanze 2-3 posters opgehangen. Wij hebben ook via een studenten vereneging een appje kunnen sturen in hun groepapp deze had dezelfde opbouw als de mail. Verder hebben wij op onze persoonlijke sociale media accounts "Instagram" nog een oproep gedaan of mensen onze enquete wilden invullen. We zijn op deze dag van 7 naar 26 antwoorden gegaan.

## 16-05-2024

Hebben wij geen kans gekregen om aan onze opdracht te werken echter hebben wij wel mails ontvangen / beantwoord

## 17-05-2024

door medische redenen kon ik deze dag niks toevoegen aan het onderzoek


